version: "3.8"
services:
  db:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    #image: bhanunexus/bitnami-postgresql-pgvector
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:snapshot
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:



#-- Enable pgvector

# create extension if not exists vector with schema extensions;
# create extension if not exists vector;


# -- Table for your chunks
# create table if not exists public.chunks (
#  id bigserial primary key,
#  doc_id text not null,
#  chunk_index int not null,
#  content text not null,
#  metadata jsonb default '{}'::jsonb,
#  embedding vector(1536) -- match your embedding dimension
# );


# -- (Recommended) cosine distance index for fast ANN search
# create index if not exists idx_chunks_embedding
#  on public.chunks using ivfflat (embedding vector_cosine_ops)
#  with (lists = 100);


# -- Simple similarity search function (with optional metadata filter)
# create or replace function public.match_documents(
#  query_embedding vector(1536),
#  match_count int default 5,
#  filter jsonb default '{}'::jsonb
# )
# returns table (
#  id bigint,
#  doc_id text,
#  chunk_index int,
#  content text,
#  metadata jsonb,
#  similarity float
# )
# language plpgsql
# stable
# as $$
# begin
#  return query
#  select
#    c.id,
#    c.doc_id,
#    c.chunk_index,
#    c.content,
#    c.metadata,
#    1 - (c.embedding <=> query_embedding) as similarity  -- cosine similarity
#  from public.chunks c
#  where (filter = '{}'::jsonb) or (c.metadata @> filter)
#  order by c.embedding <=> query_embedding               -- lower distance is better
#  limit match_count;
# end;
# $$;    